import { FilmRoll, Bundle } from "../shared/types";
import kodakImage from "@assets/generated_images/kodak_portra_film_bundle_box.png";
import fujiImage from "@assets/generated_images/fujifilm_superia_film_bundle_box.png";
import ilfordImage from "@assets/generated_images/ilford_hp5_plus_film_bundle_box.png";
import rollImage from "@assets/generated_images/generic_film_roll_canister_35mm.png";

export const INITIAL_BUNDLES: Bundle[] = [
  {
    id: "bundle_kodak_1",
    name: "Kodak Portra Professional Pack",
    image_url: kodakImage,
    film_rolls: ["roll_k1", "roll_k2", "roll_k3"],
  },
  {
    id: "bundle_fuji_1",
    name: "Fujifilm Superia Everyday Kit",
    image_url: fujiImage,
    film_rolls: ["roll_f1", "roll_f2", "roll_f3"],
  },
  {
    id: "bundle_ilford_1",
    name: "Ilford HP5 Black & White Kit",
    image_url: ilfordImage,
    film_rolls: ["roll_i1", "roll_i2"],
  },
];

export const INITIAL_ROLLS: FilmRoll[] = [
  {
    id: "roll_k1",
    name: "Kodak Portra 400",
    manufacturer: "Kodak",
    film_type: "color_negative",
    film_size: "35mm",
    expiry_date: "2025-12-31",
    iso_recommended: 400,
    iso_custom: null,
    notes: "Best for skin tones, warm daylight.",
    image_url: rollImage,
    bundle_id: "bundle_kodak_1",
  },
  {
    id: "roll_k2",
    name: "Kodak Portra 400",
    manufacturer: "Kodak",
    film_type: "color_negative",
    film_size: "120",
    expiry_date: "2026-06-30",
    iso_recommended: 400,
    iso_custom: 320,
    notes: "Shoot at 320 for better shadows.",
    image_url: rollImage,
    bundle_id: "bundle_kodak_1",
  },
  {
    id: "roll_k3",
    name: "Kodak Portra 800",
    manufacturer: "Kodak",
    film_type: "color_negative",
    film_size: "35mm",
    expiry_date: "2024-11-01",
    iso_recommended: 800,
    iso_custom: null,
    notes: "Low light situations.",
    image_url: rollImage,
    bundle_id: "bundle_kodak_1",
  },
  {
    id: "roll_f1",
    name: "Fujifilm Superia X-TRA 400",
    manufacturer: "Fujifilm",
    film_type: "color_negative",
    film_size: "35mm",
    expiry_date: null,
    iso_recommended: 400,
    iso_custom: null,
    notes: "Found in attic, expiry unknown.",
    image_url: rollImage,
    bundle_id: "bundle_fuji_1",
  },
  {
    id: "roll_f2",
    name: "Fujifilm Superia X-TRA 400",
    manufacturer: "Fujifilm",
    film_type: "color_negative",
    film_size: "35mm",
    expiry_date: "2025-01-15",
    iso_recommended: 400,
    iso_custom: null,
    notes: null,
    image_url: rollImage,
    bundle_id: "bundle_fuji_1",
  },
  {
    id: "roll_f3",
    name: "Fujifilm Superia X-TRA 400",
    manufacturer: "Fujifilm",
    film_type: "color_negative",
    film_size: "35mm",
    expiry_date: "2025-01-15",
    iso_recommended: 400,
    iso_custom: null,
    notes: null,
    image_url: rollImage,
    bundle_id: "bundle_fuji_1",
  },
  {
    id: "roll_i1",
    name: "Ilford HP5 Plus",
    manufacturer: "Ilford",
    film_type: "black_white",
    film_size: "35mm",
    expiry_date: "2027-10-10",
    iso_recommended: 400,
    iso_custom: 800,
    notes: "Push processing to 800 planned.",
    image_url: rollImage,
    bundle_id: "bundle_ilford_1",
  },
  {
    id: "roll_i2",
    name: "Ilford HP5 Plus",
    manufacturer: "Ilford",
    film_type: "black_white",
    film_size: "120",
    expiry_date: "2027-10-10",
    iso_recommended: 400,
    iso_custom: null,
    notes: null,
    image_url: rollImage,
    bundle_id: "bundle_ilford_1",
  },
];
